import * as fs from "node:fs/promises";

export async function checkPlayer({ taskSpace, url, spaceId, reportDirectory } = {}) {
if (!url || typeof taskSpace !== "function") throw new Error("Pass taskSpace and the assembled starter's file URL from ego-browser nodejs.");
const existingSpace = spaceId;
const task = await taskSpace(existingSpace ? Number(existingSpace) : "GSAP player regression");
const page = task.page("p1");
const checks = [];
const expect = (name, passed) => {
  checks.push({name, passed:Boolean(passed)});
  if (!passed) throw new Error(name);
};
const state = () => page.evaluate(() => window.explainer.getState());
const completeDiagram = () => page.evaluate(() => [...document.querySelectorAll("#scene-mechanism [data-enter], #scene-mechanism [data-draw]")].every(node => getComputedStyle(node).opacity === "1" && getComputedStyle(node).visibility === "visible"));
await page.cdp("Page.addScriptToEvaluateOnNewDocument", {source:`
  window.__playerErrors=[];
  window.addEventListener("error", event=>window.__playerErrors.push({message:event.message||"Resource failed",source:event.filename||event.target?.src||""}),true);
  window.addEventListener("unhandledrejection", event=>window.__playerErrors.push({message:String(event.reason)}));
  const originalError=console.error.bind(console);
  console.error=(...args)=>{window.__playerErrors.push({message:args.map(String).join(" ")});originalError(...args);};
`});
await page.cdp("Emulation.setDeviceMetricsOverride", {width:1280,height:1000,deviceScaleFactor:1,mobile:false});
await page.goto(url);
let current = await state();
expect("Default is a readable paused first scene", current.sceneIndex===0 && current.preview && current.fraction===1 && !current.playing);
await page.click("#next");
expect("Next presents the complete authored diagram", (await state()).sceneIndex===1 && await completeDiagram());
await page.click("#previous");
expect("Previous returns to the first scene", (await state()).sceneIndex===0);
await page.click('[data-jump="1"]');
await page.click("#toggle");
await page.waitForFunction(()=>window.explainer.getState().fraction>0.1 && window.explainer.getState().playing);
await page.click("#toggle");
current = await state();
const pausedFraction = current.fraction;
expect("Pause retains the animated frame", !current.playing && !current.preview && pausedFraction>0 && pausedFraction<1);
await page.click("#toggle");
await page.waitForFunction(fraction=>window.explainer.getState().fraction>fraction, pausedFraction);
expect("Resume advances from the paused frame", (await state()).playing);
await page.cdp("Emulation.setEmulatedMedia", {features:[{name:"prefers-reduced-motion",value:"reduce"}]});
await page.waitForFunction(()=>window.explainer.getState().reducedMotion);
current = await state();
expect("Reduced motion completes the current diagram", !current.playing && current.preview && current.fraction===1 && await completeDiagram());
await page.reload();
await page.click("#next");
expect("Initial reduced motion preserves complete manual diagrams", (await state()).reducedMotion && await completeDiagram());
await page.cdp("Emulation.setEmulatedMedia", {features:[{name:"prefers-reduced-motion",value:"no-preference"}]});
await page.waitForFunction(()=>!window.explainer.getState().reducedMotion);
expect("Normal motion does not auto-play", !(await state()).playing);
await page.evaluate(()=>{window.explainer.seek(1,0);});
expect("Delayed entrances are hidden at the start", await page.evaluate(()=>[...document.querySelectorAll("#scene-mechanism [data-enter]")].every(node=>getComputedStyle(node).opacity==="0")));
await page.evaluate(()=>{window.explainer.seek(1,0.5);});
await page.evaluate(()=>{window.explainer.seek(1,1);});
expect("Completed animation has no hidden authored targets", await completeDiagram());
await page.click("#restart");
await page.click("#scene-claim h1");
await page.keyboard.press("ArrowRight");
expect("Right shortcut navigates", (await state()).sceneIndex===1);
await page.keyboard.press("ArrowLeft");
expect("Left shortcut navigates", (await state()).sceneIndex===0);
await page.keyboard.press("Space");
await page.waitForFunction(()=>window.explainer.getState().playing);
await page.keyboard.press("Space");
expect("Space toggles playback", !(await state()).playing);
await page.keyboard.press("r");
expect("R restarts paused", (await state()).sceneIndex===0 && !(await state()).playing);
await page.press("#next","Space");
expect("Focused button activates once without hijacked shortcuts", (await state()).sceneIndex===1 && !(await state()).playing);
await page.evaluate(()=>{window.explainer.restart();gsap.globalTimeline.timeScale(15);});
await page.click("#toggle");
await page.waitForFunction(()=>window.explainer.getState().completed,undefined,{timeout:10000});
current = await state();
expect("Completion holds final scene at full progress", current.sceneIndex===2 && !current.playing && current.fraction===1 && current.percent===100);
await page.click("#toggle");
expect("Replay restarts before the final scene", !(await state()).completed);
await page.evaluate(()=>{window.explainer.pause();gsap.globalTimeline.timeScale(1);});
const custom = await page.evaluate(async()=>{
  const host=document.createElement("div");
  host.innerHTML='<section style="color:teal"><svg viewBox="0 0 30 30"><circle cx="11" cy="17" r="4"/></svg></section><section><p>Different authored layout</p></section><button data-jump="0">First</button><button data-jump="1">Second</button>';
  document.body.append(host);
  const elements=[...host.querySelectorAll("section")];
  const buttons=[...host.querySelectorAll("button")];
  const markup=elements.map(element=>element.innerHTML);
  let authoredCompletions=0;
  const player=ExplainerPlayer.create({scenes:[{element:elements[0]},{element:elements[1],createTimeline:({gsap})=>gsap.timeline({paused:true,onComplete:()=>{authoredCompletions++;}}).to({}, {duration:0.08})}],controls:{jump:[buttons[1],buttons[0]]}});
  const reordered=buttons[0].getAttribute("aria-current")==="step" && !buttons[1].hasAttribute("aria-current");
  buttons[1].click();
  const jump=player.getState().sceneIndex===1 && buttons[1].getAttribute("aria-current")==="step";
  const preserved=elements.every((element,index)=>element.innerHTML===markup[index]) && elements[0].style.color==="teal";
  player.play();
  await new Promise((resolve,reject)=>{
    const tick=()=>{if(player.getState().completed){clearTimeout(timeout);gsap.ticker.remove(tick);resolve();}};
    const timeout=setTimeout(()=>{gsap.ticker.remove(tick);player.destroy();host.remove();reject(new Error("Custom timeline did not complete"));},5000);
    gsap.ticker.add(tick);
  });
  const callbacks=authoredCompletions===1;
  player.goTo(0);
  player.destroy();
  buttons[1].click();
  const cleanup=player.getState().sceneIndex===0;
  host.remove();
  const svg=document.createElementNS("http://www.w3.org/2000/svg","svg");
  svg.innerHTML='<g><circle cx="11" cy="17" r="4"/></g><g><rect width="20" height="20"/></g>';
  const svgScenes=[...svg.children];
  const status=document.createElement("p");
  const previous=document.createElement("button");
  const next=document.createElement("button");
  const restart=document.createElement("button");
  previous.innerHTML='<span>Custom icon</span>';
  next.setAttribute("aria-label","Authored next name");
  document.body.append(svg,status);
  const svgPlayer=ExplainerPlayer.create({scenes:svgScenes.map((element,index)=>({element,title:`Vector ${index}`})),controls:{status,previous,next,restart},labels:{previous:"Earlier",restart:"Start over",previewText:(_number,_count,title)=>title,paused:(_number,_count,title)=>title}});
  const svgInitial=getComputedStyle(svgScenes[0]).display!=="none" && getComputedStyle(svgScenes[1]).display==="none";
  svgPlayer.goTo(1);
  const svgNavigation=getComputedStyle(svgScenes[0]).display==="none" && getComputedStyle(svgScenes[1]).display!=="none";
  const labels=previous.getAttribute("aria-label")==="Earlier" && next.getAttribute("aria-label")==="Authored next name" && restart.getAttribute("aria-label")==="Start over" && previous.querySelector("span")?.textContent==="Custom icon";
  const previewTitle=status.textContent==="Vector 1";
  svgPlayer.seek(1,0.5);
  const formatterTitle=previewTitle && status.textContent==="Vector 1";
  svgPlayer.destroy();svg.remove();status.remove();
  return {reordered,jump,preserved,callbacks,cleanup,svgInitial,svgNavigation,labels,formatterTitle};
});
for (const [name,passed] of Object.entries(custom)) expect(`Custom scenes: ${name}`,passed);
for (const width of [1280,375]) {
  await page.cdp("Emulation.setDeviceMetricsOverride",{width,height:850,deviceScaleFactor:1,mobile:false});
  for (let index=0;index<3;index++) {
    const layout = await page.evaluate(async index=>{
      window.explainer.goTo(index);
      await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));
      const stage=document.querySelector(".stage").getBoundingClientRect();
      const scene=document.querySelectorAll("[data-scene]")[index];
      const clipped=[...scene.querySelectorAll("h1,h2,p,svg text")].filter(node=>{const rect=node.getBoundingClientRect();return rect.left<stage.left+1||rect.top<stage.top+1||rect.right>stage.right-1||rect.bottom>stage.bottom-1;}).map(node=>node.textContent);
      return {clipped,overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth};
    },index);
    expect(`Scene ${index} fits width ${width}`, !layout.overflow && !layout.clipped.length);
  }
  if(reportDirectory) await page.screenshot({path:`${reportDirectory}/width-${width}.png`,fullPage:true});
}
expect("Normal playback has no script or console errors", await page.evaluate(()=>window.__playerErrors.length===0));
await page.cdp("Network.enable");
await page.cdp("Network.setCacheDisabled",{cacheDisabled:true});
const gsapUrl="https://cdn.jsdelivr.net/npm/gsap@3.13.0/dist/gsap.min.js";
await page.cdp("Network.setBlockedURLs",{urls:[gsapUrl]});
await page.reload();
current = await state();
expect("Missing GSAP disables playback and reports the problem", !current.gsapAvailable && await page.evaluate(()=>document.querySelector("#toggle").disabled && document.querySelector("#status").textContent.includes("GSAP")));
await page.click("#next");
expect("Missing GSAP preserves complete manual diagrams", (await state()).sceneIndex===1 && await completeDiagram());
await page.click("#previous");
await page.click('[data-jump="2"]');
expect("Fallback jump and previous work", (await state()).sceneIndex===2);
await page.click("#restart");
expect("Fallback restart works", (await state()).sceneIndex===0);
expect("Fallback errors are only the blocked CDN", await page.evaluate(url=>window.__playerErrors.every(error=>error.source===url),gsapUrl));
await page.cdp("Network.setBlockedURLs",{urls:[]});
await page.cdp("Network.setCacheDisabled",{cacheDisabled:false});
await page.cdp("Emulation.setEmulatedMedia",{features:[]});
await page.cdp("Emulation.clearDeviceMetricsOverride");
await page.reload();
expect("Restoring the network restores normal playback", (await state()).gsapAvailable && await page.evaluate(()=>window.__playerErrors.length===0));
if(reportDirectory) await fs.writeFile(`${reportDirectory}/player-checks.json`,JSON.stringify(checks,null,2));
console.log({spaceId:task.spaceId,passed:checks.length,checks});
console.log(await page.snapshot());
if(!existingSpace) await task.finish({keep:[]});
}
